title:        MHI Contractors
intro_text:   Welcome. Let's Get to Work

collections:
  projects:
    output:   true
  services:
    output:   true

defaults:
  -
    scope:
      path:   ""
      type:   projects
    values:
      layout: default
  -
    scope:
      path:   ""
      type:   services
    values:
      layout: default
